name: Docs Build Check

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v3
      -   name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: "3.11"

      -   name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements_dev.txt
            pip install -r docs/requirements.txt

      - uses: sphinx-doc/github-problem-matcher@master
      - name: "Build docs"
        run: |
          cd docs
          sphinx-build -b html . build
